version: '3.7'

services:
    web:
      build: .
      command: python /BookstoreDemo/bookstore_project/manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/BookstoreDemo
      ports:
        - 8000:8000
      depends_on:
        - db

    db:
        image: postgres:11
        volumes:
          - ./postgres-data:/var/lib/postgressql/data